SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

SCREEN_TITLE = 'Megaman 1'

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

SPRITE_START_COORD = 0, 0

DIRECTION_RIGHT = 1
DIRECTION_LEFT = -1

MEGAMAN_WALKING_RIGHT_SPRITE_SHEET = 'assets/megaman_walking_right.png'
MEGAMAN_WALKING_RIGHT_SPRITE_SHEET_SIZE = 10
MEGAMAN_WALKING_RIGHT_SPRITE_WIDTH = 64
MEGAMAN_WALKING_RIGHT_SPRITE_HEIGHT = 64

MEGAMAN_SHOOTING_RIGHT_SPRITE_SHEET = 'assets/megaman_shooting_right.png'
MEGAMAN_SHOOTING_RIGHT_SPRITE_SHEET_SIZE = 10
MEGAMAN_SHOOTING_RIGHT_SPRITE_WIDTH = 64
MEGAMAN_SHOOTING_RIGHT_SPRITE_HEIGHT = 64

MEGAMAN_JUMPING_RIGHT_SPRITE_SHEET = 'assets/megaman_jumping_right.png'
MEGAMAN_JUMPING_RIGHT_SPRITE_SHEET_SIZE = 10
MEGAMAN_JUMPING_RIGHT_SPRITE_WIDTH = 64
MEGAMAN_JUMPING_RIGHT_SPRITE_HEIGHT = 64

MEGAMAN_WALKING_LEFT_SPRITE_SHEET = 'assets/megaman_walking_left.png'
MEGAMAN_WALKING_LEFT_SPRITE_SHEET_SIZE = 10
MEGAMAN_WALKING_LEFT_SPRITE_WIDTH = 64
MEGAMAN_WALKING_LEFT_SPRITE_HEIGHT = 64

MEGAMAN_SHOOTING_LEFT_SPRITE_SHEET = 'assets/megaman_shooting_left.png'
MEGAMAN_SHOOTING_LEFT_SPRITE_SHEET_SIZE = 10
MEGAMAN_SHOOTING_LEFT_SPRITE_WIDTH = 64
MEGAMAN_SHOOTING_LEFT_SPRITE_HEIGHT = 64

MEGAMAN_JUMPING_LEFT_SPRITE_SHEET = 'assets/megaman_jumping_left.png'
MEGAMAN_JUMPING_LEFT_SPRITE_SHEET_SIZE = 10
MEGAMAN_JUMPING_LEFT_SPRITE_WIDTH = 64
MEGAMAN_JUMPING_LEFT_SPRITE_HEIGHT = 64